name: CustomDrop
main: com.brian041301.customdrop.Main
version: 2.0.0
authors: [0obrino0 , kunyihua]
website: www.youtube.com/user/brian041301
api-version: 1.13
commands:
   cdrop:
      description: CustomDrop Commands.
      permission: CustomDrop.cdrop
      permission-message: you can not use it