name: CustomDrop
main: com.kunyihua.customdrop.Main
version: 1.0.4
api-version: 1.13
commands:
   cdrop:
      description: CustomDrop Commands.
      permission: CustomDrop.cdrop
      permission-message: you can not use it